### ISSUE TITLE
Move System.js import script from <head> to <body>

### ISSUE THREAD

**Issue by AugustNagro** [joost-de-vries/play-angular2-typescript#7]
Although it doesn't appear to cause issues in your TodoMVC example application, calling System.import in the head tag can cause the application to bootstrap itself before the dom is ready. 

This has happened to me, and and [others](http://stackoverflow.com/questions/35644123/the-selector-my-app-did-not-match-any-elements). 

The solution is to move the script to the bottom of the body tag. Strangely, [Angular's own documentation](https://angular.io/docs/ts/latest/quickstart.html), shows the bootstrapping call in the head. I'm not sure if it's because Angular is still RC and the docs are being hastily written, or that they know something I don't 😕

**Comment by joost-de-vries** [comment]
Hm. Yeah, I used to do what you describe. And then I noticed that the Angular documentation doesn't do that (anymore).
I'd like to follow the Angular docs to the letter. Since the value add of this demo project and the sbt-typescript plugin that makes it possible is in the Play support for Angular. Not to show how to create Angular apps....

**Comment by AugustNagro** [comment]
Sounds fair.
