### ISSUE TITLE
Update to Angular 2 RC

### ISSUE THREAD

**Issue by KarlSjostrand** [joost-de-vries/play-angular2-typescript#8]
There are now Angular 2 RC.3 deps at http://www.webjars.org/npm. Would it be possible to update this template accordingly?

**Comment by Alcalion** [comment]
Hi there !

I started a project a few months ago and used this project to build my angular2 properly.
I can still work with the angular2 beta version but upgrading it to the RC would really help. Hence I started the update but unfortunately I keep facing the same import issue in my ts files.

I think there is a major difference in the fact that you now have to use several webjars instead of just one previously. I will keep an eye on this issue if there are any updates, and if I find a solution until then I'll come share it here.

**Comment by dragouf** [comment]
yes I faced same problem. I described it here: http://stackoverflow.com/questions/38246004/integrate-angular2-rc-with-play-framework-2

It would be very great if someone have a working example.

**Comment by joost-de-vries** [comment]
If you look into the ts-20-preview branch you'll find my upgrade to Angular 2 RC4.
At this moment I only implemented the index1 version.
